library(showtext)
fonts <- font_files()
font_add("Matura MT Script Capitals", "MATURASC.TTF")
font_add("Narkisim", "nrkis.ttf")
font_add("Vivaldi", "VIVALDII.TTF")
font_add("Gabriola", "Gabriola.ttf")
font_add("Mesquite Std", "MesquiteStd.otf")
font_add("Nyala", "nyala.ttf")
font_add("Onyx", "ONYX.TTF")
font_add("Adobe Devanagari", "AdobeDevanagari-Bold.otf")
font_add("Comic Sans MS", "comic.ttf")
showtext_opts(dpi = 300)
showtext_auto()